# Generated by Django 4.1.1 on 2022-10-01 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DbPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=50)),
                ('botanical_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=150)),
                ('time_till_dry', models.IntegerField()),
                ('added_at', models.DateField(auto_now_add=True)),
                ('published', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OwnedPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('public', models.BooleanField(default=False)),
                ('healthy', models.BooleanField(default=True)),
                ('watered', models.BooleanField(default=False)),
                ('adopted_since', models.DateField(auto_now_add=True)),
                ('comments', models.TextField(max_length=150)),
                ('type', models.ManyToManyField(to='main_app.dbplant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
