# Generated by Django 4.1.1 on 2022-10-03 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ownedplant_watering_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedplant',
            name='adopted_since',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ownedplant',
            name='watering_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
