# Generated by Django 4.1.1 on 2022-10-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_ownedplant_adopted_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedplant',
            name='comments',
            field=models.TextField(default='No comments yet', max_length=150),
        ),
        migrations.AlterField(
            model_name='ownedplant',
            name='type',
            field=models.ManyToManyField(limit_choices_to={'published': True}, to='main_app.dbplant'),
        ),
    ]
