# Generated by Django 4.1.1 on 2022-10-08 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_ownedplant_type_ownedplant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownedplant',
            name='type',
            field=models.ForeignKey(limit_choices_to={'published': True}, on_delete=django.db.models.deletion.CASCADE, related_name='plant_type', to='main_app.dbplant'),
        ),
    ]
