# Generated by Django 4.1.2 on 2022-10-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_cat_photo_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dbplant')),
            ],
        ),
    ]
